"""Setup models on database

Revision ID: 0dc5983c6902
Revises: 7ccfe0675591
Create Date: 2023-03-29 20:45:43.973071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc5983c6902'
down_revision = '7ccfe0675591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
