"""Setup models on database

Revision ID: 2145a1191d67
Revises: e2c09e1196c3
Create Date: 2023-03-29 20:06:02.724353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2145a1191d67'
down_revision = 'e2c09e1196c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
