"""Setup models on database

Revision ID: 21d0215c899c
Revises: 8584459a0cb6
Create Date: 2023-03-29 18:27:06.320758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d0215c899c'
down_revision = '8584459a0cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
