"""Setup models on database

Revision ID: 4c587fad4cac
Revises: 67239a26e459
Create Date: 2023-03-29 18:56:13.145532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c587fad4cac'
down_revision = '67239a26e459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
