"""Setup models on database

Revision ID: 5c4901278fa4
Revises: 21d0215c899c
Create Date: 2023-03-29 18:36:31.069364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4901278fa4'
down_revision = '21d0215c899c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
