"""Setup models on database

Revision ID: 6109cd79fdf0
Revises: f1e464eec3f3
Create Date: 2023-03-29 19:10:55.555159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6109cd79fdf0'
down_revision = 'f1e464eec3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
