"""Setup models on database

Revision ID: 67239a26e459
Revises: ae22760b545a
Create Date: 2023-03-29 18:54:03.206967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67239a26e459'
down_revision = 'ae22760b545a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
