"""Setup models on database

Revision ID: 7ccfe0675591
Revises: f68f49ed2ae2
Create Date: 2023-03-29 20:43:42.831481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccfe0675591'
down_revision = 'f68f49ed2ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
