"""Setup models on database

Revision ID: 8885cbf27e22
Revises: 2145a1191d67
Create Date: 2023-03-29 20:11:54.842724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8885cbf27e22'
down_revision = '2145a1191d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
