"""Setup models on database

Revision ID: 895f2236b85d
Revises: fbee9393309e
Create Date: 2023-03-29 20:16:58.267008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895f2236b85d'
down_revision = 'fbee9393309e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
