"""Setup models on database

Revision ID: 8db645a6b05d
Revises: 895f2236b85d
Create Date: 2023-03-29 20:26:31.420221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db645a6b05d'
down_revision = '895f2236b85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
