"""Setup models on database

Revision ID: 9c829b67b5cf
Revises: 8db645a6b05d
Create Date: 2023-03-29 20:31:13.706053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c829b67b5cf'
down_revision = '8db645a6b05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
