"""Setup models on database

Revision ID: a7f77f10ba3c
Revises: b2e35189beac
Create Date: 2023-03-29 19:43:32.281071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f77f10ba3c'
down_revision = 'b2e35189beac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
