"""Setup models on database

Revision ID: ae22760b545a
Revises: d1f0e67c15fc
Create Date: 2023-03-29 18:50:19.070243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae22760b545a'
down_revision = 'd1f0e67c15fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
