"""Setup models on database

Revision ID: b2e35189beac
Revises: 6109cd79fdf0
Create Date: 2023-03-29 19:19:00.363018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e35189beac'
down_revision = '6109cd79fdf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
