"""Setup models on database

Revision ID: d028fab1e48f
Revises: 4c587fad4cac
Create Date: 2023-03-29 19:00:41.079204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd028fab1e48f'
down_revision = '4c587fad4cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
