"""Setup models on database

Revision ID: deaf9e65471b
Revises: 0dc5983c6902
Create Date: 2023-03-29 20:54:58.471540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deaf9e65471b'
down_revision = '0dc5983c6902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
