"""Setup models on database

Revision ID: e2c09e1196c3
Revises: a7f77f10ba3c
Create Date: 2023-03-29 20:03:39.032427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c09e1196c3'
down_revision = 'a7f77f10ba3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
