"""Setup models on database

Revision ID: f1e464eec3f3
Revises: d028fab1e48f
Create Date: 2023-03-29 19:03:54.399202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e464eec3f3'
down_revision = 'd028fab1e48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
