"""Setup models on database

Revision ID: f68f49ed2ae2
Revises: fbd6d60fbc55
Create Date: 2023-03-29 20:38:14.427510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68f49ed2ae2'
down_revision = 'fbd6d60fbc55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
