"""Setup models on database

Revision ID: fbd6d60fbc55
Revises: 9c829b67b5cf
Create Date: 2023-03-29 20:35:42.411701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd6d60fbc55'
down_revision = '9c829b67b5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
