"""Setup models on database

Revision ID: fbee9393309e
Revises: 8885cbf27e22
Create Date: 2023-03-29 20:13:41.973166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbee9393309e'
down_revision = '8885cbf27e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
